import Head from "next/head";

import { api } from "@/utils/api";
import { Sidebar } from "@/components/sidebar";
import { Board } from "@/server/db/schema";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import AddTaskModal from "@/components/add-task-modal";
import { getFromLocalStorage } from "@/hooks/useLocalStorage";

export default function Home() {
  const currentBoard = getFromLocalStorage<Board>("selectedBoard");

  const { data, isLoading, isError, error } = api.main.getAllTasks.useQuery(
    {
      id: currentBoard?.id!,
    },
    {
      enabled: !!currentBoard,
    },
  );

  return (
    <>
      <Head>
        <title>Kanban Board</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen overflow-hidden">
        <Sidebar />
        <section className="flex-1 bg-gray-100 p-6">
          <header className="mb-6 flex items-center justify-between border-b-2 pb-5">
            <h1 className="text-3xl font-bold capitalize">
              {currentBoard?.title ?? "Select a board"}
            </h1>
            <AddTaskModal />
          </header>
        </section>
      </main>
    </>
  );
}
